"""Xymphony Voice shared domain contracts (Pydantic). No vendor SDKs."""

from xymphony_contracts.agent import Agent, AgentVersion
from xymphony_contracts.content import ContentPart
from xymphony_contracts.enums import (
    AgentStatus,
    AgentVersionStatus,
    Channel,
    ContentPartType,
    EventSource,
    EventType,
    InterruptReason,
    MessageRole,
    MessageStatus,
    SessionEndReason,
    SessionStatus,
    TurnStatus,
    UsageUnit,
)
from xymphony_contracts.events import (
    ENVELOPE_SCHEMA_VERSION,
    STALE_IF_TURN_CANCELLED,
    TURN_SCOPED_EVENT_TYPES,
    AgentInterruptedPayload,
    AudioFramePayload,
    ErrorPayload,
    Event,
    LLMResponsePayload,
    LLMTokenPayload,
    SessionEndedPayload,
    SessionStartedPayload,
    TranscriptFramePayload,
    TTSChunkPayload,
    UserSpeechEndedPayload,
    UserSpeechStartedPayload,
    validate_sequence_monotonic,
)
from xymphony_contracts.llm import (
    CancellationToken,
    LLMMessage,
    LLMProvider,
    LLMRequest,
    LLMResponse,
    LLMRole,
    LLMStreamChunk,
    LLMToolCall,
    LLMToolDefinition,
    ProviderError,
    ProviderErrorCode,
)
from xymphony_contracts.persistence import (
    ConversationRepository,
    ConversationSummaryRepository,
    CreateSessionRequest,
    SessionRepository,
)
from xymphony_contracts.providers import LLMBinding, STTBinding, TTSBinding
from xymphony_contracts.session import Message, Session, Turn
from xymphony_contracts.stt import (
    STTAudioFormat,
    STTAudioFrame,
    STTProvider,
    STTRequest,
    STTTranscriptChunk,
)
from xymphony_contracts.summary import ConversationSummary
from xymphony_contracts.tools import ToolErrorCode, ToolResult
from xymphony_contracts.tts import (
    TTSProvider,
    TTSRequest,
    TTSResponse,
    TTSStreamChunk,
    TTSTextRange,
)
from xymphony_contracts.usage import Usage

__all__ = [
    "ENVELOPE_SCHEMA_VERSION",
    "STALE_IF_TURN_CANCELLED",
    "TURN_SCOPED_EVENT_TYPES",
    "Agent",
    "AgentInterruptedPayload",
    "AgentStatus",
    "AgentVersion",
    "AgentVersionStatus",
    "AudioFramePayload",
    "Channel",
    "ContentPart",
    "ContentPartType",
    "ConversationRepository",
    "ConversationSummary",
    "ConversationSummaryRepository",
    "CreateSessionRequest",
    "ErrorPayload",
    "Event",
    "EventSource",
    "EventType",
    "InterruptReason",
    "CancellationToken",
    "LLMBinding",
    "LLMMessage",
    "LLMProvider",
    "LLMRequest",
    "LLMResponse",
    "LLMResponsePayload",
    "LLMRole",
    "LLMStreamChunk",
    "LLMToolCall",
    "LLMToolDefinition",
    "LLMTokenPayload",
    "ProviderError",
    "ProviderErrorCode",
    "Message",
    "MessageRole",
    "MessageStatus",
    "STTBinding",
    "STTAudioFormat",
    "STTAudioFrame",
    "STTProvider",
    "STTRequest",
    "STTTranscriptChunk",
    "Session",
    "SessionEndReason",
    "SessionEndedPayload",
    "SessionRepository",
    "SessionStartedPayload",
    "SessionStatus",
    "TTSBinding",
    "TTSChunkPayload",
    "TTSProvider",
    "TTSRequest",
    "TTSResponse",
    "TTSStreamChunk",
    "TTSTextRange",
    "ToolErrorCode",
    "ToolResult",
    "TranscriptFramePayload",
    "Turn",
    "TurnStatus",
    "Usage",
    "UsageUnit",
    "UserSpeechEndedPayload",
    "UserSpeechStartedPayload",
    "validate_sequence_monotonic",
]
